name: Build Firmware, Electron (v1.5.2)
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/supermileage/particle-v1.5.2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: app

      - name: Build
        run: |
          cd /firmware/main && make all PLATFORM=electron APPDIR=$GITHUB_WORKSPACE/app TARGET_DIR=/out

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: /out
