name: Build Firmware
on: [push, pull_request]

jobs:
  build-urban:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 5

      - name: Diff Source
        uses: marceloprado/has-changed-path@v1
        id: changed
        with:
          paths: urban
      
      - name: Diff Libraries
        uses: marceloprado/has-changed-path@v1
        id: lib-changed
        with:
          paths: lib

      - name: Build
        if: steps.changed.outputs.changed == 'true' || steps.lib-changed.outputs.changed == 'true'
        run: |
          make urban

      - name: Upload
        if: steps.changed.outputs.changed == 'true' || steps.lib-changed.outputs.changed == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: urban-${{ github.sha }}
          path: output

  build-proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 5

      - name: Diff Source
        uses: marceloprado/has-changed-path@v1
        id: changed
        with:
          paths: proto
      
      - name: Diff Libraries
        uses: marceloprado/has-changed-path@v1
        id: lib-changed
        with:
          paths: lib

      - name: Build
        if: steps.changed.outputs.changed == 'true' || steps.lib-changed.outputs.changed == 'true'
        run: |
          make proto

      - name: Upload
        if: steps.changed.outputs.changed == 'true' || steps.lib-changed.outputs.changed == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: proto-${{ github.sha }}
          path: output
